application: ucls-mayproject
runtime: python27
api_version: 1
version: staging 
threadsafe: no

builtins:
- remote_api: on

libraries:
- name: jinja2
  version: latest

handlers:
- url: /dump
  login: admin
  script: main.dump
- url: /
  script: main.index
  secure: always
- url: /bootstrap.min.css
  static_files: bootstrap.min.css
  upload: bootstrap.min.css
- url: /bootstrap.min.js
  static_files: bootstrap.min.js
  upload: bootstrap.min.js
- url: /bootstrap-responsive.css
  static_files: bootstrap-responsive.css
  upload: bootstrap-responsive.css
- url: /api/create
  script: main.create_user
  secure: always
- url: /api/login
  script: main.authenticate_user
  secure: always
- url: /api/exit
  script: main.exit_submit
  secure: always
- url: /exit
  script: main.exit_view
  secure: always
- url: /user
  script: main.user_view
  secure: always 
- url: /img
  static_dir: img
- url: /api/logout
  script: main.logout
  secure: always
- url: /submit
  script: main.submit_view
  secure: always
- url: /api/upload
  script: main.upload
  secure: always
- url: /[approve|deny]+(/[0-9]+) 
  script: main.account_auth
  secure: always
- url: /api/forms
  script: main.forms_update
  secure: always
- url: /download+(/[0-9]+)
  script: main.download_proposal
  secure: always
- url: /review/start
  script: main.start_review
  secure: always
- url: /review+(/[0-9]+)
  script: main.review_proposal
  secure: always
- url: /api/view
  script: main.coordinator_view
  secure: always
- url: /view+(/[0-9]+)
  script: main.view_proposal
  secure: always
- url: /api/modify
  script: main.modify_reviewers
  secure: always
