application: ucls-mayproject
runtime: python27
api_version: 1
version: staging
threadsafe: yes

libraries:
- name: jinja2
  version: latest

handlers:
- url: /
  script: main.index
  secure: always
- url: /bootstrap.min.css
  static_files: bootstrap.min.css
  upload: bootstrap.min.css
- url: /bootstrap.min.js
  static_files: bootstrap.min.js
  upload: bootstrap.min.js
- url: /bootstrap-responsive.css
  static_files: bootstrap-responsive.css
  upload: bootstrap-responsive.css
- url: /api/create
  script: main.create_user
  secure: always
- url: /api/login
  script: main.authenticate_user
  secure: always
- url: /user
  script: main.user_view
  secure: always 
- url: /img
  static_dir: img
- url: /api/logout
  script: main.logout
  secure: always
- url: /submit
  script: main.submit_view
  secure: always
